// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVH4Dao7E_zhihmdrDk9QGh9_Anu3Tq3E',
    appId: '1:1048925915327:web:aec464ab5a1a091e5c9e0a',
    messagingSenderId: '1048925915327',
    projectId: 'project-carrito2b',
    authDomain: 'project-carrito2b.firebaseapp.com',
    storageBucket: 'project-carrito2b.firebasestorage.app',
    measurementId: 'G-V7C7TVGH6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn-Ttq7-TWEnSNXRYQrHAJT9AXnj1WauU',
    appId: '1:1048925915327:android:6b8e27dde8d5f65b5c9e0a',
    messagingSenderId: '1048925915327',
    projectId: 'project-carrito2b',
    storageBucket: 'project-carrito2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5bQ62JW3XFvAf582SqsHyxOZvGfd4qOE',
    appId: '1:1048925915327:ios:62f6d838d05649835c9e0a',
    messagingSenderId: '1048925915327',
    projectId: 'project-carrito2b',
    storageBucket: 'project-carrito2b.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp2b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5bQ62JW3XFvAf582SqsHyxOZvGfd4qOE',
    appId: '1:1048925915327:ios:62f6d838d05649835c9e0a',
    messagingSenderId: '1048925915327',
    projectId: 'project-carrito2b',
    storageBucket: 'project-carrito2b.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp2b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVH4Dao7E_zhihmdrDk9QGh9_Anu3Tq3E',
    appId: '1:1048925915327:web:dee79edcf0f732e75c9e0a',
    messagingSenderId: '1048925915327',
    projectId: 'project-carrito2b',
    authDomain: 'project-carrito2b.firebaseapp.com',
    storageBucket: 'project-carrito2b.firebasestorage.app',
    measurementId: 'G-J85J2QC2S1',
  );

}